### ISSUE TITLE
i++이 먼가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#1]
여기서 i++이 어떤 건가요???

```js
for (var i = 0; i < 10; i++) {
 // ...
}
```

**Comment by nainde0719** [comment]
i++ 를 간단하게 설명하면 i에 값이 1 증가 하는 것이다.
i가 0이라면 i++ 하면 i는 1이 된다.
i++는 i = i + 1; 를 줄여놓은 것과 같다.

**Comment by captaintailer** [comment]
i++ 를 간단하게 설명하면 i에 값이 1 증가 하는 것이다.
i가 0이라면 i++ 하면 i는 1이 된다.
i++는 i = i + 1; 를 줄여놓은 것과 같다.
