### ISSUE TITLE
033. 심볼형 이해하기 P.103

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#10]
이해를 못하겠어요.^^;;

```js
const symbol = Symbol ();
const hello = Symbol('hello');

console.log(Number(3) === Number(3));
console.log(Symbol('symbol') === Symbol('symbol'));
console.log(Symbol() === Symbol());
console.log(typeof Symbol());

const nationility = Symbol('nationility');
const user = {
    name: 'jay'
};
user[nationility] = 'korean';
console.log(user[nationility]);

for (let key in user) {
    console.log(key);
}
console.log(Object.keys(user));
console.log(Object.getOwnPropertyNames(user));
console.log(JSON.stringify(user));

const symbolProperties = Object.getOwnPropertySymbols(user);
console.log(symbolProperties);
console.log(user[symbolProperties[0]]);
```

(1라인)
심볼(Symbol)은 함수 호출을 통해 생성가능하다. new 키워들를 통한 호출(new Symbol())을 할 경우 에러가 발생한다.

(2~7)
Symbol을 함수 호출 시 값을 전달할 수 있는데 이 값은 디버깅 용도이며 고유한 Symbol 값은 만들어지지 않는다. 즉, Symbol()은 늘 고유한 값을 반환한다. 그래서 5~6라인은 false가 된다. typeof 연산자를 통해 심볼형을 확인할 수 있다.

(9~14)
심볼은 객체의 키로 사용 가능하다. 객체의 키로 사용하기 위해선 Symbol에 대한 레퍼런스를 변수에 담고 있다가 접근할 때마다 사용해야 한다.

(16~18)
심볼이 객체의 키로 사용되면 for-in 루프를 통해 심볼 키를 가져올 수 없다.

(19~21)
그렇기 때문에 Object의 키를 반환하는 메소드를 사용해도 가져올 수 없고, JSON 문자열로 만들 때에도 해당 키는 빠지게 된다.

(23~25)
심볼을 객체의 키로 사용할 때 해당 키를 가져올 방법이 없는 것은 아니다. Object.getOwnPropertySymbols 메소드를 통해 해당 객체의 키에 해당하는 심볼들을 가져올 수 있다.

**Comment by rosd89** [comment]
> (1라인)
> 심볼(Symbol)은 함수 호출을 통해 생성가능하다. new 키워들를 통한 호출(new Symbol())을 할 경우 에러가 발> 생한다.

Symbol은 js의 기본 자료형이기 때문입니다.
`https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Symbol`

**Comment by rosd89** [comment]
Symbol을 이해하기 위해서 객체를 이해해야합니다.
