### ISSUE TITLE
034. 함수 이해하기 p.105

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#11]
Nainde는 `모르겠다` 를 시전했다!

```js
var greeting_expression = function(name) {
    console.log('Hi, ' + name);
}

function greeting_declaration(name) {
    console.log('Hi, ' + name);
}

greeting_expression('Chloe');
greeting_declaration('Chloe');
```

(1~3)
함수 표현식으로 함수를 만든다. 함수를 정희하면서 동시에 변수 greeting_expression에 바로 할당한다. 다시 말해, greeting_expression 변수에 함수 리터럴을 할당한다.

(5~7)
함수 선언문은 일반적인 다른 개발 언어와 비슷한 함수 선언 방식으로, greeting_declaration이라는 함수 이름으로 선언한다.

(9~10)
함수를 호출할 때는 함수 리터럴이 할당된 변수 이름 또는 함수 선언문의 함수 이름이 필요하다. 주의할 점은 함수 표현식에서 정의한 함수 이름은 해당 함수 안에서만 호출 가능하다. 그리고 선언된 함수가 매개변수를 필요로 하는 경우 소괄호 () 안에 전달할 값을 나열한다. greeting_expression 함수와 greeting_declaration 함수는 정의한 방식이 다르지만, 실행부 코드와 매개변수 목록이 같다. 동일한 "Chloe" 인자를 전달하여 각 함수를 호출한다.

**Comment by rosd89** [comment]
js의 함수는 일급함수입니다. 함수를 값으로 판별 할 수 있기에 변수에 저장하는 것이 가능합니다.

정확한 질문이 멀까요?

**Comment by nainde0719** [comment]
> Nainde는 `모르겠다` 를 시전했다!
> 
> ```js
> var greeting_expression = function(name) {
>     console.log('Hi, ' + name);
> }
> 
> function greeting_declaration(name) {
>     console.log('Hi, ' + name);
> }
> 
> greeting_expression('Chloe');
> greeting_declaration('Chloe');
> ```
> 
> (1~3)
> 함수 표현식으로 함수를 만든다. 함수를 정희하면서 동시에 변수 greeting_expression에 바로 할당한다. 다시 말해, greeting_expression 변수에 함수 리터럴을 할당한다.
> 
> (5~7)
> 함수 선언문은 일반적인 다른 개발 언어와 비슷한 함수 선언 방식으로, greeting_declaration이라는 함수 이름으로 선언한다.
> 
> (9~10)
> 함수를 호출할 때는 함수 리터럴이 할당된 변수 이름 또는 함수 선언문의 함수 이름이 필요하다. 주의할 점은 함수 표현식에서 정의한 함수 이름은 해당 함수 안에서만 호출 가능하다. 그리고 선언된 함수가 매개변수를 필요로 하는 경우 소괄호 () 안에 전달할 값을 나열한다. greeting_expression 함수와 greeting_declaration 함수는 정의한 방식이 다르지만, 실행부 코드와 매개변수 목록이 같다. 동일한 "Chloe" 인자를 전달하여 각 함수를 호출한다.
