### ISSUE TITLE
매개 변수란 무엇인가요? + 메소드는 무엇인가요? + 이 코드는 무얼하고 싶은 건가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#13]
```js
function sum(...args) {
    var total = 0;
    for (var i = 0; i < args.length; i++) {
        total += args[i];
    }
    console.log(args.indexOf(1))
    return total;
}
console.log(sum(1, 2, 3));

function sum2(a, b, ...others) {
    var total = a+b;
    for (var i = 0; i < others.length; i ++) {
        total += others[i];
    }
    return total;
}
console.log(sum2(1, 2));
console.log(sum2(1, 2, 3, 4));
```

1~9
sum 함수를 나머지 매개변수로 정의하고 있다. 나머지 매개변수인 args는 배열이기 때문에 [인덱스]를 통해 접근이 가능하고 indexOF와 같은 메소드를 사용할 수 있다. 9라인에서 전달한 1, 2, 3 전달 인자들은 args 배열이 되고 배열을 순차적으로 접근하여 total 변수값과 더하면서 그 결과를 바로 대입한다. 마지막으로 전체 합계인 total을 반환한다.

18
sum2 함수 호출 시 a와 b 매개변수에 1과 2로 인자들을 전달하고 있다. 이때 others는 빈 배열이 된다.
19
sum2 함수 호출 시 a와 b 두 매개변수보다 더 많은 인자가 전달되기 때문에 1과 2는 각각 a와 b에 전달되고 나머지 3과 3는 others 나머지 매개변수의 배열의 요소로 전달된다.

**Comment by rosd89** [comment]
> 메개 변수란 무엇인가요?

매개 변수는 보통 => `parameter`를 가르킵니다.
위의 코드에서는 sum 함수의 인자를 말합니다.

위에서 사용된 인자를 정의하는 방법은 `spread operator`라고 es6이후에 생긴 구문입니다.

사용되는 위치에 따라 부르는 이름이나 역할이 조금씩 다릅니다.
- 함수 정의부에서 인자를 정의 할 때 - `rest parameter`
- 함수 호출 부, 연산시 등등 - `spread operator`

관련문서

`rest parameter` 문서
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Functions/rest_parameters

`spread operator` 문서
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Spread_syntax

**Comment by rosd89** [comment]
> 메소드는 무엇인가요?

메소드는 함수와 비슷하지만 한자기 다른점이 있습니다.
바로 객체안의 정의된 함수를 메서드라고 칭합니다.

지금은 함수라고만 이해하셔도 괜찮습니다.

**Comment by rosd89** [comment]
> + 이 코드는 무얼하고 싶은 건가요?

위 코드는 입력된 인자를 다 더하는 함수인데 `rest parameter`을 설명하기 위해서 만들어진 코드라고 생각됩니다.
