### ISSUE TITLE
"전역" 이 뭔가요? p.116

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#14]
자바스크립트는 기본적으로 전역과 함수 단위로 스코프를 생성한다. 함수 안에서 선언된 함수는 함수 블록 안에서만 접근이 가능하다. 그리고 전역에 선언한 변수들은 코드 어디에든 접근이 가능하다.

**Comment by rosd89** [comment]
전역은 어디서나 접근이 가능하다 정도로 아시고 패스!
