### ISSUE TITLE
컨텍스트와 렉시컬 환경이 무엇인가요? p.125

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#17]
자바스크립트에서 스코프 체인을 이해하기 위해서는 실행 컨텍스트와 렉시컬 환경에 대해 먼저 알아야 한다.

실행 컨텍스트는 코드가 실행되기 위해 필요한 정보를 가지고 있다. 이 실행 컨텍스트는 실행 가능한 코드가 실행될 때 생성된다. 대표적인 실행 가능한 코드로는 전역 코드와 함수 코드가 있다. 그 외에 eval과 모듈 코드도 있다.

처음에는 전역 코드가 먼저 실행된다. 이때 전역 컨텍스트를 만들고 전역 코드를 순차적으로 평가한다. 그러나 함수가 호출문을 만나면 새로운 실행 컨텍스트가 만들어지면서 해당 함수 실행부의 코드를 순차적으로 평가한다. 이때 스택을 이용해 실행 컨텍스트를 관리하게 되는데, 새로운 실행 컨텍스트가 생성되면 스택에 쌓고 실행 중인 코드가 종료되면 해당 실행 컨텍스트를 스택에서 제거한다.

실행 컨텍스트는 렉시컬 환경을 가지고 있는데, 렉시컬 환경은 환경 레코드와 외부 렉시컬 환경으로 구성된다.

**Comment by rosd89** [comment]
이거 패스 매년 버전이 올라 갈 때마다 조금씩 바뀌는 부분이라서 지금은 패스
