### ISSUE TITLE
(!h || !h.city) 의미가 뭐였죠

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#2]
```js
var hometown = [
    { name: '남준', place: '일산', city: '고양' },
    { name: '진', place: '과천' },
    { name: '호석', place: '광주', city: '전라도' },
    { name: '지민', place: '부산', city: '경상도' }
];

for (var i = 0; i < hometown.length; i++) {
    var h = hometown[i];
    if (!h || !h.city) continue;

    console.log(i + ' 번째 실행입니다.');

    if (h.name === '호석') {
        console.log ( h.name + '의 고향은' + h.city + ' '+h.place+' 입니다.')
        break;
    }
}
```

**Comment by rosd89** [comment]
`var h = hometown[i]`
위 코드에서 h값을 대입했을 때 h값이 `null`/`undefinde`인지 확인하기 위해서 `if`문에서 먼저 `h`의 값을 체크합니다.

`h`의 값이 `false`라면 아래의 코드를 실행 할 필요가 없으니 `continue` 실행

그 후에 `h.city` 값이 없다면 아래의 코드를 실행 할 필요가 없으니 `continue` 실행

**Comment by nainde0719** [comment]
`h`의 값이 `false`라는 게 `h` 값이 없다면 이라는 뜻인가요?

만약 `h`값이 없다면 이라면
(!h || !h.city) 는 `h`의 값이 없거나 `!h.city`의 값이 없다면  `continue` 실행하라는 건가요?

**Comment by rosd89** [comment]
> `h`의 값이 `false`라는 게 `h` 값이 없다면 이라는 뜻인가요?

네 맞습니다.

> 만약 `h`값이 없다면 이라면
> (!h || !h.city) 는 `h`의 값이 없거나 `!h.city`의 값이 없다면 `continue` 실행하라는 건가요?

h의 값이 있다면 h.city의 값이 있는지를 확인 후 없다면 continue를 실행합니다.
