### ISSUE TITLE
프로토타입 기반과 자바의 클래스 기반이란 무엇인가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#20]
p.140
자바스크립트는 프로토타입 기반으로 객체지향 프로그래밍을 지원한다. 자바의 클래스 기반과의 큰 차이점으로 프로토타입으로 객체에 공통 사항을 적용할 수 있다. 즉, 모든 객체는 다른 객체의 원형이 될 수 있다. 특징을 묘사하는 원형 객체를 만들고 이 원형 객체에 기반하는 여러 객체들을 만들면 모두 같은 특징을 가질 수 있다.

Q2. 모든 객체는 다른 객체의 원형이 될 수 있다는 것은 얼추 이해가 되는데 모두 같은 특징을 가질 수 있다는 건 잘 이해가 안되네요.

**Comment by rosd89** [comment]
일단 패스 이거 설명하다간 이 페이지에서 다 안 끝납니다.

자바와는 객체를 생성하는 방법이 다르다 정도로 이해하시면 될 것 같습니다.
