### ISSUE TITLE
결과가 [object Object] 라고 나오는 이유가 뭔가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#22]
072. 문자열로 변환하기(toString) p.203

```js
const obj = {a: 15};

console.log(obj.toString());
```

**Comment by rosd89** [comment]
![image](https://user-images.githubusercontent.com/11239348/78380376-b9f9d880-760e-11ea-96c2-ffeca0ef9206.png)

Object 타입이니까요....

[관련문서]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/toString

**Comment by rosd89** [comment]
![image](https://user-images.githubusercontent.com/11239348/78380661-2d034f00-760f-11ea-9d56-9d67cdbba71e.png)

물론 원하는 형태로 재정의해서 쓰는 방법도 있는데 별로 추천하고 싶지는 않습니다.
