### ISSUE TITLE
el 이 뭐예요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#23]
079.js 배열 요소를 분할/변환하기(from)
```js
const str = '12345678';

const distributedArr = Array.from(str);
console.log(distributedArr);

const modifiedArr = Array.from(distributedArr, el => el * 2);
console.log(modifiedArr);
```

**Comment by rosd89** [comment]
![image](https://user-images.githubusercontent.com/11239348/78380044-3c35cd00-760e-11ea-8207-24a144fc2238.png)

`Array.from`은 두번째 인자로 익명함수를 전달 받을 수 있습니다.
역할은 첫번째 인자로 전달 받은 배열의 모든 요소를 순회하여 실행합니다.

이 때 `el`은 첫번째 인자로 받아온 배열의 각 요소의 값입니다.

[관련문서]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/from

공통적으로 익명함수에 대한 이해가 부족해보입니다.
