### ISSUE TITLE
s.split 에 s 는 무슨 의미인가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#24]
080. 문자열을 특정 구분자에 의해 배열로 나누기(split) p.213
```js
const capitals = `Prague,Czech Republic
Copenhagen,Denmark
Paris,France
Madrid,Spain
Rome,Italy`

capitals.split('\n').forEach(s => {
    const capital = s.split(',')[0];
    const country = s.split(',')[1];
    console.log(`${capital} is in ${country}`);
});
```

**Comment by rosd89** [comment]
`split`는 `String.prototype`의 내장함수로 입력받은 구분자를 기반으로 문자열을 나눠 배열을 반환합니다.

[관련문서]
`split`
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/split

**Comment by rosd89** [comment]
```js
capitals.split('\n').forEach(s => {
    const capital = s.split(',')[0];
    const country = s.split(',')[1];
    console.log(`${capital} is in ${country}`);
});
```

위의 코드를 보면 `\n` 구분자로 문자열을 나눠 반환된 배열을 순회하는 코드입니다. 
`s`는 `foreach` 문서를 참고하시면 됩니다.

`\n` enter의 escape문자

[관련문서]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
