### ISSUE TITLE
slice 메소드에 시작-끝 인덱스로 2, 3을 넣으면 왜 'source'가 반환되나요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#25]
088.배열 특정 위치의 요소 추출하기(slice) p.223
```js
const arr = ['melon', 'lemon', 'source', 'apple', 'juice'];
console.log(`과일이 아닌 요소는 ${arr.slice(2, 3)}와 ${arr.slice(4,5)} 입니다.`);
console.log(arr.slice(0, 10));
```

**Comment by rosd89** [comment]
`slice`는 배열에서 원하는 요소를 포함한 새로운 배열을 반환하는 `Array. prototype`입니다.

첫번째 인자는 start 인덱스 위치를 지정합니다. (0으로 시작)
두번째 인자는 end 인덱스 위치를 지정합니다. (0으로 시작)

[참고문서]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/slice
