### ISSUE TITLE
'use strict'란 무엇인가요? + changeUntiNum 은 무엇인가요? + num이 number 30을 가리키는지 어떻게 아는 건가요? 밑에 정의된 let profile과 changeUntiNum(profile(=지연), 30(=25))에서 가져오는 건가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#26]
104. 객체 변경되지 않도록 하기 (freeze) p.245

```js
let obj = {};

obj.title = 'IDOL';
obj = Object.freeze(obj);
obj.title = 'Euphoria';

console.log(obj);

const changeUntiNum = (obj, num) => {
    'use strict';

    while(true) {
        console.log(obj);

        if (obj.age >= num) {
            obj = Object.freeze(obj);
        }
        obj.age += 1;
    }
};

let profile = {name: '지연', age: 25};
changeUntiNum(profile, 30);
```

**Comment by rosd89** [comment]
질문을 내용에 아래와 같이 정리해주세요.
1. use strict가 무언인가요?
2. changeUntiNum은 무엇인가요?
3. num이 number 30을 가리키는지 어떻게 아는 건가요? 밑에 정의된 let profile과 changeUntiNum(profile(=지연), 30(=25))에서 가져오는 건가요?

위의 코드는 `Object.freeze`를 설명하기 위해서 만들어진 코드로 보입니다.

[관련문서]
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by rosd89** [comment]
use strict가 무언인가요?

아래 문서를 읽어보세요.

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Strict_mode

**Comment by rosd89** [comment]
changeUntiNum은 무엇인가요?

첫번째 인자 obj의 age가 두번째 인자와 같을 때 오브젝트를 수정하지 못하도록 `freeze`를 걸어주는 함수입니다.

일단 `while(true) { ... }` 해당 코드는 종료 조건이 없기 때문에 무한루프를 돌게됩니다.

매번 age의 값을 +1씩 더해주는 역할을 합니다.

여기서 두번째 인자(30)일 때 `freeze`가 걸리기 때문에 그 다음 시도에서는 에러가 납니다.

 
![image](https://user-images.githubusercontent.com/11239348/78734033-1e57c780-7982-11ea-8018-d17dc58123d9.png)

strict mode에서는 freeze가 걸려있는 Object를 수정하면 예외를 뱉어내기 때문에 위와같이 에러가 나면서 프로그램이 종료되게 됩니다.

**Comment by rosd89** [comment]
num이 number 30을 가리키는지 어떻게 아는 건가요? 밑에 정의된 let profile과 changeUntiNum(profile(=지연), 30(=25))에서 가져오는 건가요?

changeUntiNum 함수 실행시 첫번째 인자로 profile, 두번째 인자로 30을 넣어주기 때문입니다.
