### ISSUE TITLE
JSON이 뭐예요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#31]
JavaScript Object Notation)은 속성-값 쌍( attribute–value pairs and array data types (or any other serializable value)) 또는 "키-값 쌍"으로 이루어진 데이터 오브젝트를 전달하기 위해 인간이 읽을 수 있는 텍스트를 사용하는 개방형 표준 포맷이다.

JSON이랑 JSON 문자열의 차이도 알려주세요!!

**Comment by rosd89** [comment]
데이터를 표현하는 하나의 방법입니다. 요즘날 제일 많이 사용하는 데이터 표현방식입니다.
그 구조가 key:value를 쌍으로 지니는 오브젝트의 구조로 되어있습니다.

관련 문서
https://www.json.org/json-ko.html

**Comment by nainde0719** [comment]
@rosd89 
JSON 과 JSON 문자열은 다른건가요?
