### ISSUE TITLE
ishometown 이 뭐예요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#4]
```js
var hometown = [
    {name: '진', city: '과천'},
    {name: '남준', place: '일산', city: '고양'},
    {name: '호석', place: '광주', city: '전라도'},
    {name: '지민', place: '부산', city: '경상도'},
];

var isHometown = function(h, name) {
    console.log(`함수가 실행되었습니다. ${h.city} 도시에서 ${name} 을 찾습니다.`);

    if (h.name === name) {
        console.log(`${h.name} 의 고향은 ${h.city} ${h.place} 입니다.`);
        return true;
    }
    return false;
}

var h;
while (h = hometown.shift()) {
    if (!h.name || !h.place || !h.city) continue;

    var result = isHometown(h, '호석');
    if (result) break;
}

var i = 0;
var names = ['남준', '정국', '윤기', '호섭'];
var cities = ['경기', '부산', '대구', '광주'];
do {
    hometown[i] = {name: names[i], city: cities[i]};
    i++;
} while (i < 4);

console.log(hometown);
```

**Comment by rosd89** [comment]
보통 코드에서 `isXXXXX`인 변수명이나 함수는 `true`/`false`를 값으로 지닙니다.

위 코드에서는 `isHometown`은 인자 `h.name`의 값과 `name`의 값이 같은지 판별하는 함수입니다. 

```js
var result = isHometown(h, '호석');
```

i가 0일 때 h의 값
h == `{name: '진', city: '과천'}`
`isHometown(h, '호석')`의 반환 값은 `false`

i가 1일 때 h의 값
h == `{name: '남준', place: '일산', city: '고양'}`
`isHometown(h, '호석')`의 반환 값은 `false`

i가 2일 때 h의 값
h == `{name: '호석', place: '광주', city: '전라도'}`
`isHometown(h, '호석')`의 반환 값은 `true`

i가 2일 때 h의 값
h == `{name: '지민', place: '부산', city: '경상도'}`
`isHometown(h, '호석')`의 반환 값은 `false`

**Comment by nainde0719** [comment]
다음에 만나서 다시 설명들어야 겠어요 허허, 알듯말듯 하네요..

**Comment by rosd89** [comment]
> 다음에 만나서 다시 설명들어야 겠어요 허허, 알듯말듯 하네요..

어제 물어보시지 ㅋㅋㅋ
