### ISSUE TITLE
>> 비트 연산자 와 >>> 비트 연산자의 차이가 뭔가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#6]
결과값이 계속 같아요 ㅠ

**Comment by rosd89** [comment]
이건 몰라도 괜찮습니다.

**Comment by rosd89** [comment]
![image](https://user-images.githubusercontent.com/11239348/77143535-dd793b00-6ac6-11ea-9068-ed4380b7b48f.png)

관련문서
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators
