### ISSUE TITLE
 코드가 어떻게 돌아가는지 잘 모르겠어요. + 비구조화 할당이란 게 무슨 말인가요?

### ISSUE THREAD

**Issue by nainde0719** [nainde0719/study_javascript#9]
032. 배열 비구조화 할당 p.101

배열 비구조화 할당은 객체 비구조화 방식에서 중괄호를 대괄호 []로 바꾸면 된다. 객체의 경우와 비슷하게 여러 값을 한 번에 가져올 수 있다.
```js
//032-1.js
var arr = [ 1, 2, 30, 44, 5];

var [b, c, ...rest] = arr;
console.log(`0) b >>> ${b}`);
console.log(`0) c >>> ${c}`);
console.log(`0) rest >>> ${rest}`);

var [a=10, f=9] = [1];
console.log(`1) a >>> ${a}`);
    console.log(`1) f >>> ${f}`);

function getArr() {
    return [1, 2, 3, 4, 5, 6];
}
[a, , , , , f] = getArr();
console.log(`3) a >>> ${a}`);
console.log(`3) f >>> ${f}`);
```

(4~5 번째 줄 설명)
arr 배열에 숫자형 요소들이 5개 대입되어 있습니다. 배열을 비구조화 할 때는 대관호를 사용하며 대괄호 안의 변수에 배열 요소가 순서대로 하나씩 할당됩니다.

따라서 b 변수에는 첫 번째 요소 1, c 변수에는 두 번째 요소 2가 대입된 것입니다. 그리고 나머지 변수 지시자 ...를 활용하면, 6라인의 rest 변수처럼 나머지 값들을 한꺼번에 따로 담을 수 있습니다. 따라서 rest 변수에는 b, c 값 이외의 나머지 [30, 44, 5]이 할당됩니다.

(8~14)
배열 비구조화에서도 기본값 설정이 가능합니다. 배열값 [1]을 비구조화 하면 a 변수에 첫 번째 요소 1이 할당됩니다. 두 번째 f 변수에는 해당 순서의 요소가 없으므로 기본값 9가 할당됩니다.

(16~21)
함수에서 반환된 배열값을 비구조화 할 수 있습니다. 또한 일부 배열 요소를 무시하고, 원하는 요소만 가져오는 것도 가능합니다. 19라인처럼 중간에 4개 요소를 반환받고 싶지 않을 때, 해당 위치의 요소는 콤마 사이에 공백으로 비워두면 됩니다. 따라서 첫 번째 요소 1이 a 변수에 할당되고, 마지막 요소 6이 F 변수에 할당됩니다.

**Comment by rosd89** [comment]
`destructuring`은 array/objet를 해체하여 원하는 요소를 정의하는 구문입니다. 동작원리에 대한 질문은 아닐거 같아 사용법이 담긴 문서를 첨부합니다.

관련문서
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
